"""phase6_goals_tora_conversation

Revision ID: 0e6386aa6927
Revises: 80f9e8b135b5
Create Date: 2026-03-16 03:37:38.640056

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = '0e6386aa6927'
down_revision = '80f9e8b135b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_goal',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_goal_id'), 'finance_goal', ['id'], unique=False)
    op.create_index(op.f('ix_finance_goal_user_id'), 'finance_goal', ['user_id'], unique=False)
    op.create_table('tora_conversation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=2000), nullable=False),
    sa.Column('financial_overview', sa.String(length=2000), nullable=True),
    sa.Column('current_position', sa.String(length=2000), nullable=True),
    sa.Column('recommended_strategy', sa.String(length=4000), nullable=True),
    sa.Column('expected_outcome', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tora_conversation_created_at'), 'tora_conversation', ['created_at'], unique=False)
    op.create_index(op.f('ix_tora_conversation_id'), 'tora_conversation', ['id'], unique=False)
    op.create_index(op.f('ix_tora_conversation_user_id'), 'tora_conversation', ['user_id'], unique=False)
    op.drop_table('alembic_version_auth')
    op.drop_index('ix_auth_user_username', table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key')
    )
    op.create_index('ix_auth_user_username', 'auth_user', ['username'], unique=True)
    op.create_table('alembic_version_auth',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_auth_pkc')
    )
    op.drop_index(op.f('ix_tora_conversation_user_id'), table_name='tora_conversation')
    op.drop_index(op.f('ix_tora_conversation_id'), table_name='tora_conversation')
    op.drop_index(op.f('ix_tora_conversation_created_at'), table_name='tora_conversation')
    op.drop_table('tora_conversation')
    op.drop_index(op.f('ix_finance_goal_user_id'), table_name='finance_goal')
    op.drop_index(op.f('ix_finance_goal_id'), table_name='finance_goal')
    op.drop_table('finance_goal')
    # ### end Alembic commands ###
