"""add_confidence_to_transaction

Revision ID: 0f8f7a931768
Revises: 20260321_01
Create Date: 2026-03-24 03:20:28.321126

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = '0f8f7a931768'
down_revision = '20260321_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_health',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('savings_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('stability_index', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('debt_to_income', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_health_id'), 'finance_health', ['id'], unique=False)
    op.create_index(op.f('ix_finance_health_user_id'), 'finance_health', ['user_id'], unique=True)
    op.create_table('finance_insight',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_expense', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('category_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('merchant_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'period', name='uq_user_period_insight')
    )
    op.create_index(op.f('ix_finance_insight_id'), 'finance_insight', ['id'], unique=False)
    op.create_index(op.f('ix_finance_insight_user_id'), 'finance_insight', ['user_id'], unique=False)
    op.create_table('finance_recommendation',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=True),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_recommendation_id'), 'finance_recommendation', ['id'], unique=False)
    op.create_index(op.f('ix_finance_recommendation_uid'), 'finance_recommendation', ['uid'], unique=True)
    op.create_index(op.f('ix_finance_recommendation_user_id'), 'finance_recommendation', ['user_id'], unique=False)
    op.create_table('finance_useralert',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_useralert_id'), 'finance_useralert', ['id'], unique=False)
    op.create_index(op.f('ix_finance_useralert_user_id'), 'finance_useralert', ['user_id'], unique=False)
    # Add confidence as nullable first to avoid NotNullViolation on existing rows
    op.add_column('finance_transaction', sa.Column('confidence', sa.Integer(), nullable=True))
    # Backfill all existing rows with default confidence of 100
    op.execute("UPDATE finance_transaction SET confidence = 100 WHERE confidence IS NULL")
    # Now enforce NOT NULL
    op.alter_column('finance_transaction', 'confidence', nullable=False)
    op.alter_column('finance_userprofile', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finance_userprofile', 'tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('finance_transaction', 'confidence')
    op.drop_index(op.f('ix_finance_useralert_user_id'), table_name='finance_useralert')
    op.drop_index(op.f('ix_finance_useralert_id'), table_name='finance_useralert')
    op.drop_table('finance_useralert')
    op.drop_index(op.f('ix_finance_recommendation_user_id'), table_name='finance_recommendation')
    op.drop_index(op.f('ix_finance_recommendation_uid'), table_name='finance_recommendation')
    op.drop_index(op.f('ix_finance_recommendation_id'), table_name='finance_recommendation')
    op.drop_table('finance_recommendation')
    op.drop_index(op.f('ix_finance_insight_user_id'), table_name='finance_insight')
    op.drop_index(op.f('ix_finance_insight_id'), table_name='finance_insight')
    op.drop_table('finance_insight')
    op.drop_index(op.f('ix_finance_health_user_id'), table_name='finance_health')
    op.drop_index(op.f('ix_finance_health_id'), table_name='finance_health')
    op.drop_table('finance_health')
    # ### end Alembic commands ###
