"""add_loan_id_to_finance_plan

Revision ID: 2b006fc92769
Revises: 56496704cc52
Create Date: 2026-03-29 09:22:15.930502

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = '2b006fc92769'
down_revision = '56496704cc52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_plan', sa.Column('loan_id', sa.BigInteger(), nullable=True))
    op.add_column('finance_transaction', sa.Column('account_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_transaction', 'account_type')
    op.drop_column('finance_plan', 'loan_id')
    # ### end Alembic commands ###
