"""Add debit card model and update credit card

Revision ID: 80f9e8b135b5
Revises: 6b4b4d46c405
Create Date: 2026-03-15 19:03:53.298554

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = '80f9e8b135b5'
down_revision = '6b4b4d46c405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_debitcard',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_debitcard_id'), 'finance_debitcard', ['id'], unique=False)
    op.create_index(op.f('ix_finance_debitcard_user_id'), 'finance_debitcard', ['user_id'], unique=False)
    op.drop_index('ix_auth_user_username', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('alembic_version_auth')
    op.drop_table('alembic_version')
    op.create_index(op.f('ix_finance_apiauditlog_id'), 'finance_apiauditlog', ['id'], unique=False)
    op.add_column('finance_creditcard', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('finance_creditcard', sa.Column('card_holder_name', sa.String(length=100), nullable=False))
    op.add_column('finance_creditcard', sa.Column('last_four_digits', sa.String(length=4), nullable=False))
    op.add_column('finance_creditcard', sa.Column('billing_cycle', sa.Integer(), nullable=True))
    op.add_column('finance_creditcard', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('finance_creditcard', 'current_balance')
    op.drop_column('finance_creditcard', 'name')
    op.drop_column('finance_creditcard', 'billing_day')
    op.drop_constraint('finance_itrdata_user_id_key', 'finance_itrdata', type_='unique')
    op.create_index(op.f('ix_finance_itrdata_id'), 'finance_itrdata', ['id'], unique=False)
    op.drop_constraint('finance_taxprofile_user_id_key', 'finance_taxprofile', type_='unique')
    op.create_index(op.f('ix_finance_taxprofile_id'), 'finance_taxprofile', ['id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_id'), 'finance_transaction', ['id'], unique=False)
    op.drop_constraint('finance_userprofile_user_id_key', 'finance_userprofile', type_='unique')
    op.create_index(op.f('ix_finance_userprofile_id'), 'finance_userprofile', ['id'], unique=False)
    op.create_index(op.f('ix_finance_wealthitem_id'), 'finance_wealthitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_wealthitem_id'), table_name='finance_wealthitem')
    op.drop_index(op.f('ix_finance_userprofile_id'), table_name='finance_userprofile')
    op.create_unique_constraint('finance_userprofile_user_id_key', 'finance_userprofile', ['user_id'])
    op.drop_index(op.f('ix_finance_transaction_id'), table_name='finance_transaction')
    op.drop_index(op.f('ix_finance_taxprofile_id'), table_name='finance_taxprofile')
    op.create_unique_constraint('finance_taxprofile_user_id_key', 'finance_taxprofile', ['user_id'])
    op.drop_index(op.f('ix_finance_itrdata_id'), table_name='finance_itrdata')
    op.create_unique_constraint('finance_itrdata_user_id_key', 'finance_itrdata', ['user_id'])
    op.add_column('finance_creditcard', sa.Column('billing_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finance_creditcard', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('finance_creditcard', sa.Column('current_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_column('finance_creditcard', 'created_at')
    op.drop_column('finance_creditcard', 'billing_cycle')
    op.drop_column('finance_creditcard', 'last_four_digits')
    op.drop_column('finance_creditcard', 'card_holder_name')
    op.drop_column('finance_creditcard', 'bank_name')
    op.drop_index(op.f('ix_finance_apiauditlog_id'), table_name='finance_apiauditlog')
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('alembic_version_auth',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_auth_pkc')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key')
    )
    op.create_index('ix_auth_user_username', 'auth_user', ['username'], unique=True)
    op.drop_index(op.f('ix_finance_debitcard_user_id'), table_name='finance_debitcard')
    op.drop_index(op.f('ix_finance_debitcard_id'), table_name='finance_debitcard')
    op.drop_table('finance_debitcard')
    # ### end Alembic commands ###
