"""Add debit card model and update credit card

Revision ID: 80f9e8b135b5
Revises: 6b4b4d46c405
Create Date: 2026-03-15 19:03:53.298554

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = '80f9e8b135b5'
down_revision = '6b4b4d46c405'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_debitcard',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('last_four_digits', sa.String(length=4), nullable=False),
    sa.Column('card_holder_name', sa.String(length=100), nullable=False),
    sa.Column('expiry_date', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_debitcard_id'), 'finance_debitcard', ['id'], unique=False)
    op.create_index(op.f('ix_finance_debitcard_user_id'), 'finance_debitcard', ['user_id'], unique=False)

    op.create_index(op.f('ix_finance_apiauditlog_id'), 'finance_apiauditlog', ['id'], unique=False)
    op.add_column('finance_creditcard', sa.Column('bank_name', sa.String(length=100), nullable=False))
    op.add_column('finance_creditcard', sa.Column('card_holder_name', sa.String(length=100), nullable=False))
    op.add_column('finance_creditcard', sa.Column('last_four_digits', sa.String(length=4), nullable=False))
    op.add_column('finance_creditcard', sa.Column('billing_cycle', sa.Integer(), nullable=True))
    op.add_column('finance_creditcard', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('finance_creditcard', 'current_balance')
    op.drop_column('finance_creditcard', 'name')
    op.drop_column('finance_creditcard', 'billing_day')
    op.drop_constraint('finance_itrdata_user_id_key', 'finance_itrdata', type_='unique')
    op.create_index(op.f('ix_finance_itrdata_id'), 'finance_itrdata', ['id'], unique=False)
    op.drop_constraint('finance_taxprofile_user_id_key', 'finance_taxprofile', type_='unique')
    op.create_index(op.f('ix_finance_taxprofile_id'), 'finance_taxprofile', ['id'], unique=False)
    op.create_index(op.f('ix_finance_transaction_id'), 'finance_transaction', ['id'], unique=False)
    op.drop_constraint('finance_userprofile_user_id_key', 'finance_userprofile', type_='unique')
    op.create_index(op.f('ix_finance_userprofile_id'), 'finance_userprofile', ['id'], unique=False)
    op.create_index(op.f('ix_finance_wealthitem_id'), 'finance_wealthitem', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_wealthitem_id'), table_name='finance_wealthitem')
    op.drop_index(op.f('ix_finance_userprofile_id'), table_name='finance_userprofile')
    op.create_unique_constraint('finance_userprofile_user_id_key', 'finance_userprofile', ['user_id'])
    op.drop_index(op.f('ix_finance_transaction_id'), table_name='finance_transaction')
    op.drop_index(op.f('ix_finance_taxprofile_id'), table_name='finance_taxprofile')
    op.create_unique_constraint('finance_taxprofile_user_id_key', 'finance_taxprofile', ['user_id'])
    op.drop_index(op.f('ix_finance_itrdata_id'), table_name='finance_itrdata')
    op.create_unique_constraint('finance_itrdata_user_id_key', 'finance_itrdata', ['user_id'])
    op.add_column('finance_creditcard', sa.Column('billing_day', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('finance_creditcard', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('finance_creditcard', sa.Column('current_balance', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_column('finance_creditcard', 'created_at')
    op.drop_column('finance_creditcard', 'billing_cycle')
    op.drop_column('finance_creditcard', 'last_four_digits')
    op.drop_column('finance_creditcard', 'card_holder_name')
    op.drop_column('finance_creditcard', 'bank_name')
    op.drop_index(op.f('ix_finance_apiauditlog_id'), table_name='finance_apiauditlog')

    op.drop_index(op.f('ix_finance_debitcard_user_id'), table_name='finance_debitcard')
    op.drop_index(op.f('ix_finance_debitcard_id'), table_name='finance_debitcard')
    op.drop_table('finance_debitcard')
    # ### end Alembic commands ###
