"""Add status and reconciliation_flags to Transaction

Revision ID: 8a1528141186
Revises: 0f8f7a931768
Create Date: 2026-03-26 02:45:27.796704

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = '8a1528141186'
down_revision = '0f8f7a931768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transaction', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('finance_transaction', sa.Column('reconciliation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_transaction', 'reconciliation_flags')
    op.drop_column('finance_transaction', 'status')
    # ### end Alembic commands ###
