"""add_file_metadata_and_document_table

Revision ID: 20260317_05
Revises: f790b3d0ee6a
Create Date: 2026-03-17 14:07:34.834634

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = '20260317_05'
down_revision = 'f790b3d0ee6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_document',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('metadata_json', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_document_file_hash'), 'finance_document', ['file_hash'], unique=False)
    op.create_index(op.f('ix_finance_document_id'), 'finance_document', ['id'], unique=False)
    op.create_index(op.f('ix_finance_document_uid'), 'finance_document', ['uid'], unique=True)
    op.create_index(op.f('ix_finance_document_user_id'), 'finance_document', ['user_id'], unique=False)
    
    op.add_column('finance_statementrecord', sa.Column('uid', sa.String(length=36), nullable=True))
    op.add_column('finance_statementrecord', sa.Column('file_size', sa.BigInteger(), nullable=True))
    op.add_column('finance_statementrecord', sa.Column('file_hash', sa.String(length=64), nullable=True))
    
    # Populate existing rows with UIDs
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("UPDATE finance_statementrecord SET uid = uuid_generate_v4() WHERE uid IS NULL")
    
    op.create_index(op.f('ix_finance_statementrecord_file_hash'), 'finance_statementrecord', ['file_hash'], unique=False)
    op.create_index(op.f('ix_finance_statementrecord_uid'), 'finance_statementrecord', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_statementrecord_uid'), table_name='finance_statementrecord')
    op.drop_index(op.f('ix_finance_statementrecord_file_hash'), table_name='finance_statementrecord')
    op.drop_column('finance_statementrecord', 'file_hash')
    op.drop_column('finance_statementrecord', 'file_size')
    op.drop_column('finance_statementrecord', 'uid')
    
    op.drop_index(op.f('ix_finance_document_user_id'), table_name='finance_document')
    op.drop_index(op.f('ix_finance_document_uid'), table_name='finance_document')
    op.drop_index(op.f('ix_finance_document_id'), table_name='finance_document')
    op.drop_index(op.f('ix_finance_document_file_hash'), table_name='finance_document')
    op.drop_table('finance_document')
    # ### end Alembic commands ###
