"""add_bank_name_to_loan

Revision ID: 3be1fbcda5c7
Revises: 2b006fc92769
Create Date: 2026-03-29 09:31:05.726014

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = '3be1fbcda5c7'
down_revision = '2b006fc92769'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_loan', sa.Column('bank_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_loan', 'bank_name')
    # ### end Alembic commands ###
