"""Add finance_plan table

Revision ID: 56496704cc52
Revises: 8a1528141186
Create Date: 2026-03-28 23:27:53.252089

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = '56496704cc52'
down_revision = '8a1528141186'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_plan',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_saved', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('monthly_saving', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('daily_saving', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_plan_id'), 'finance_plan', ['id'], unique=False)
    op.create_index(op.f('ix_finance_plan_uid'), 'finance_plan', ['uid'], unique=True)
    op.create_index(op.f('ix_finance_plan_user_id'), 'finance_plan', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_plan_user_id'), table_name='finance_plan')
    op.drop_index(op.f('ix_finance_plan_uid'), table_name='finance_plan')
    op.drop_index(op.f('ix_finance_plan_id'), table_name='finance_plan')
    op.drop_table('finance_plan')
    # ### end Alembic commands ###
