"""Add phase 1 and 2 models

Revision ID: 6b4b4d46c405
Revises: 20260310_04
Create Date: 2026-03-15 09:28:46.917361

"""
# pyright: reportMissingImports=false
from __future__ import annotations

from alembic import op
import sqlalchemy as sa  # type: ignore

from sqlalchemy.dialects import postgresql  # type: ignore


revision = '6b4b4d46c405'
down_revision = '20260310_04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_creditcard',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('billing_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_creditcard_id'), 'finance_creditcard', ['id'], unique=False)
    op.create_index(op.f('ix_finance_creditcard_user_id'), 'finance_creditcard', ['user_id'], unique=False)
    op.create_table('finance_loan',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('loan_type', sa.String(length=20), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('emi_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('remaining_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_loan_id'), 'finance_loan', ['id'], unique=False)
    op.create_index(op.f('ix_finance_loan_user_id'), 'finance_loan', ['user_id'], unique=False)
    op.create_table('finance_networthsnapshot',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_networthsnapshot_id'), 'finance_networthsnapshot', ['id'], unique=False)
    op.create_index(op.f('ix_finance_networthsnapshot_user_id'), 'finance_networthsnapshot', ['user_id'], unique=False)
    op.create_table('finance_statementrecord',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('reconciliation_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_statementrecord_id'), 'finance_statementrecord', ['id'], unique=False)
    op.create_index(op.f('ix_finance_statementrecord_user_id'), 'finance_statementrecord', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_statementrecord_user_id'), table_name='finance_statementrecord')
    op.drop_index(op.f('ix_finance_statementrecord_id'), table_name='finance_statementrecord')
    op.drop_table('finance_statementrecord')
    op.drop_index(op.f('ix_finance_networthsnapshot_user_id'), table_name='finance_networthsnapshot')
    op.drop_index(op.f('ix_finance_networthsnapshot_id'), table_name='finance_networthsnapshot')
    op.drop_table('finance_networthsnapshot')
    op.drop_index(op.f('ix_finance_loan_user_id'), table_name='finance_loan')
    op.drop_index(op.f('ix_finance_loan_id'), table_name='finance_loan')
    op.drop_table('finance_loan')
    op.drop_index(op.f('ix_finance_creditcard_user_id'), table_name='finance_creditcard')
    op.drop_index(op.f('ix_finance_creditcard_id'), table_name='finance_creditcard')
    op.drop_table('finance_creditcard')
    # ### end Alembic commands ###
