"""Add SecurityAlert model

Revision ID: f790b3d0ee6a
Revises: 0e6386aa6927
Create Date: 2026-03-17 03:06:00.114179

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql


revision = 'f790b3d0ee6a'
down_revision = '0e6386aa6927'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_securityalert',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actor_identity', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_securityalert_actor_identity'), 'finance_securityalert', ['actor_identity'], unique=False)
    op.create_index(op.f('ix_finance_securityalert_id'), 'finance_securityalert', ['id'], unique=False)

    # Manual adjustment for existing finance rows
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")

    tables_to_update = [
        'finance_creditcard',
        'finance_debitcard',
        'finance_goal',
        'finance_loan',
        'finance_transaction',
        'finance_wealthitem'
    ]

    for table in tables_to_update:
        op.add_column(table, sa.Column('uid', sa.String(length=36), nullable=True))
        op.execute(f"UPDATE {table} SET uid = uuid_generate_v4() WHERE uid IS NULL")
        op.create_index(op.f(f'ix_{table}_uid'), table, ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_wealthitem_uid'), table_name='finance_wealthitem')
    op.drop_column('finance_wealthitem', 'uid')
    op.drop_index(op.f('ix_finance_transaction_uid'), table_name='finance_transaction')
    op.drop_column('finance_transaction', 'uid')
    op.drop_index(op.f('ix_finance_loan_uid'), table_name='finance_loan')
    op.drop_column('finance_loan', 'uid')
    op.drop_index(op.f('ix_finance_goal_uid'), table_name='finance_goal')
    op.drop_column('finance_goal', 'uid')
    op.drop_index(op.f('ix_finance_debitcard_uid'), table_name='finance_debitcard')
    op.drop_column('finance_debitcard', 'uid')
    op.drop_index(op.f('ix_finance_creditcard_uid'), table_name='finance_creditcard')
    op.drop_column('finance_creditcard', 'uid')
    op.drop_index(op.f('ix_finance_securityalert_id'), table_name='finance_securityalert')
    op.drop_index(op.f('ix_finance_securityalert_actor_identity'), table_name='finance_securityalert')
    op.drop_table('finance_securityalert')
    # ### end Alembic commands ###
