class ErrorCode:
    BAD_REQUEST = "BAD_REQUEST"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"
    RATE_LIMITED = "RATE_LIMITED"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    INVALID_TRANSACTION_TYPE = "INVALID_TRANSACTION_TYPE"
    INVALID_WEALTH_TYPE = "INVALID_WEALTH_TYPE"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    INVALID_PROFILE_DATA = "INVALID_PROFILE_DATA"
    INVALID_TAX_PROFILE = "INVALID_TAX_PROFILE"
    INVALID_ITR_PAYLOAD = "INVALID_ITR_PAYLOAD"
    INVALID_TAX_REGIME = "INVALID_TAX_REGIME"

    MISSING_FILE = "MISSING_FILE"
    PARSER_UNAVAILABLE = "PARSER_UNAVAILABLE"
    PARSER_INVALID_RESPONSE = "PARSER_INVALID_RESPONSE"
    PARSER_ERROR = "PARSER_ERROR"

    INTERNAL_ERROR = "INTERNAL_ERROR"
    OCR_REQUIRED = "OCR_REQUIRED"
