# Generated by Django 6.0.2 on 2026-02-22 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_aiinsight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIInsight',
        ),
    ]
