"""add_refresh_token_table

Revision ID: 20260317_01
Revises: dfb75467a0df
Create Date: 2026-03-17 13:50:21.413436

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = '20260317_01'
down_revision = 'dfb75467a0df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_refreshtoken',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_refreshtoken_id'), 'auth_refreshtoken', ['id'], unique=False)
    op.create_index(op.f('ix_auth_refreshtoken_jti'), 'auth_refreshtoken', ['jti'], unique=True)
    op.create_index(op.f('ix_auth_refreshtoken_user_id'), 'auth_refreshtoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_refreshtoken_user_id'), table_name='auth_refreshtoken')
    op.drop_index(op.f('ix_auth_refreshtoken_jti'), table_name='auth_refreshtoken')
    op.drop_index(op.f('ix_auth_refreshtoken_id'), table_name='auth_refreshtoken')
    op.drop_table('auth_refreshtoken')
    # ### end Alembic commands ###
