"""Add SecurityAlert and ApiAuditLog models

Revision ID: dfb75467a0df
Revises: 20260316_00
Create Date: 2026-03-17 02:52:36.262080

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa




revision = 'dfb75467a0df'
down_revision = '20260316_00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_apiauditlog',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_apiauditlog_id'), 'auth_apiauditlog', ['id'], unique=False)
    op.create_index(op.f('ix_auth_apiauditlog_request_id'), 'auth_apiauditlog', ['request_id'], unique=False)
    op.create_table('auth_securityalert',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('actor_identity', sa.String(length=64), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_securityalert_actor_identity'), 'auth_securityalert', ['actor_identity'], unique=False)
    op.create_index(op.f('ix_auth_securityalert_id'), 'auth_securityalert', ['id'], unique=False)

    # Manual adjustment for existing auth_user records
    op.add_column('auth_user', sa.Column('uid', sa.String(length=36), nullable=True))
    op.add_column('auth_user', sa.Column('role', sa.String(length=20), nullable=True))

    # Populate existing rows
    op.execute("UPDATE auth_user SET role = 'user' WHERE role IS NULL")
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("UPDATE auth_user SET uid = uuid_generate_v4() WHERE uid IS NULL")

    # Now make them non-nullable
    op.alter_column('auth_user', 'role', nullable=False)
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_uid'), 'auth_user', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_user_uid'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_column('auth_user', 'role')
    op.drop_column('auth_user', 'uid')
    op.drop_index(op.f('ix_auth_securityalert_id'), table_name='auth_securityalert')
    op.drop_index(op.f('ix_auth_securityalert_actor_identity'), table_name='auth_securityalert')
    op.drop_table('auth_securityalert')
    op.drop_index(op.f('ix_auth_apiauditlog_request_id'), table_name='auth_apiauditlog')
    op.drop_index(op.f('ix_auth_apiauditlog_id'), table_name='auth_apiauditlog')
    op.drop_table('auth_apiauditlog')
    # ### end Alembic commands ###
